#!/bin/sh

usage()
{
cat << EOF
usage: $0 options

OPTIONS:
   -h      Show this message
   -i      Module index (1: Charts, 2: Options, 3: OptionPurchase, 4: Critters)
EOF
}

MODULE="0"
while getopts “hi:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         i)
             MODULE=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

case $MODULE in

    1) JS="elm-charts"
        ;;

    2) JS="elm-options"
        ;;

    3) JS="elm-optionpurchases"
        ;;

    4) JS="elm-critters"
        ;;

    5) JS="elm-projects"
        ;;
esac

SRC_JS=$JS.js
TMP_JS=$JS.tmp.js
MIN_JS=$JS.min.js

echo "$SRC_JS -> $TMP_JS -> $MIN_JS"

uglifyjs elm-charts.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=elm-charts.min.js


exit 0
