#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

OPTIONS:
   -h      Show this message
   -m      Module (1: Maunaloa, 2: OptionPurchase)
EOF
}

MODULE=

while getopts “hm:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         m)
             MODULE=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

case $MODULE in

    1)  TARGET="dist/ps-maunaloa.js"
        spago bundle-app --to $TARGET
        # sed -i '$ d' $TARGET 
        ;;

    2) spago bundle-app --main OptionPurchaseMain --to dist/ps-optionpurchase.js
        ;;

esac

exit 0
