#!/bin/bash

TARGET=dist/ps-optionpurchase.js
#TARGET=dist/ps-maunaloa.js

#spago bundle-app --main HarborView/OptionPurchase/Main --to $TARGET
spago bundle-app --main OptionPurchaseMain --to $TARGET

# sed -i '$ d' $TARGET 

exit 0
