#!/bin/bash

#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

OPTIONS:
   -h      Show this message
   -m      Module (1: Maunaloa, 2: OptionPurchase)
EOF
}

MODULE=

while getopts “hm:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         m)
             MODULE=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

case $MODULE in

    1)  python ../python/deploy-ps-chart.py
        ;;

    2)  JS=dist/ps-optionpurchase.js
        cp $JS ../src/resources/public/js/maunaloa/
        ;;

esac

exit 0
